---
title: "Parte A"
output: html_notebook
---
```{r}

# Import libraries

library(dplyr) 
library(readr)
library(caret)
library(ggplot2)


# Read dataset 
trees_dataset <- read_csv("arbolado-mza-dataset.csv")


trainset <- trees_dataset
# Índices de la muestra de entrenamiento
trainIndex <- createDataPartition(as.factor(trainset$inclinacion_peligrosa),p=0.80,list=FALSE)
data_train <- trainset[ trainIndex, ]
data_test <- trainset[ -trainIndex, ]


# Export to csv
# write.csv(data_train,"arbolado-publico-mendoza-2021-train.csv")
# write.csv(data_test,"arbolado-publico-mendoza-2021-validation.csv")

data_train

# Plot distribution

distribution <- data_train %>% group_by(inclinacion_peligrosa) %>% summarise(total=n())

distribution

ggplot(distribution,aes(x=inclinacion_peligrosa,y=total)) +
  geom_bar(stat="identity")+
   theme(axis.text.x = element_text(angle = 45, hjust = 1))

# Plot zone danger distribution
zone_distribution <- data_train %>% filter(inclinacion_peligrosa == 1) %>% group_by(nombre_seccion) %>% summarise(total=n())

zone_distribution

# Plot distribution

ggplot(zone_distribution,aes(x=nombre_seccion,y=total)) +
  geom_bar(stat="identity")+
   theme(axis.text.x = element_text(angle = 45, hjust = 1))

# Residencial norte resulta la zona con una mayor cantidad de árboles peligrosos

# Plot species distribution 

species_distribution <- data_train %>% filter(inclinacion_peligrosa == 1) %>% group_by(especie) %>% summarise(total=n())

species_distribution

# Plot distribution

ggplot(species_distribution,aes(x=especie,y=total)) +
  geom_bar(stat="identity")+
   theme(axis.text.x = element_text(angle = 45, hjust = 1))


```

```{r}
# Import libraries

library(dplyr) 
library(readr)
library(caret)
library(ggplot2)

# Read dataset 
treesDataset <- read_csv("arbolado-mza-dataset.csv")


trainset <- treesDataset

trainset

circ_arr <- trainset$circ_tronco_cm

hist(circ_arr)

filteredSet <- treesDataset %>% filter(inclinacion_peligrosa == 1) 

filtered_circ <- filteredSet$circ_tronco_cm

hist(filtered_circ)

# Add categorical filter

trainset <- treesDataset %>% mutate(circ_tronco_cm_cat= ifelse(`circ_tronco_cm`<=100,'bajo',
                                                               ifelse(`circ_tronco_cm`>100 & `circ_tronco_cm` <= 200, 'medio',
                                                                      ifelse(`circ_tronco_cm` > 200 & `circ_tronco_cm` <= 300, 'alto','muy alto'))))

write.csv(trainset,"arbolado-publico-mendoza-2021-circ_tronco_cm-train.csv")

```

```{r}

library(dplyr) 
library(readr)

# Load dataset 

treesDataset <- read_csv("arbolado-mza-dataset.csv")

rows <- nrow(treesDataset)

rows

# Generate random probability

prob_arr <- runif(rows, 0, 1)

# Add column containing probability array to data frame

treesDataset$prediction_prob <- prob_arr

treesDataset

# Assign class

classifiedDataSet <- treesDataset %>% mutate(prediction_class = ifelse(`prediction_prob` >= 0.5, 1 ,0))

classifiedDataSet

# Calculate metrics

truePositive <- classifiedDataSet %>% filter(inclinacion_peligrosa == 1 & prediction_class == 1)

trueNegative <- classifiedDataSet %>% filter(inclinacion_peligrosa == 0 & prediction_class == 0)

falsePositive <- classifiedDataSet %>% filter(inclinacion_peligrosa == 0 & prediction_class == 1)

falseNegative <- classifiedDataSet %>% filter(inclinacion_peligrosa == 1 & prediction_class == 0)

tpCount <- nrow(truePositive)

tnCount <- nrow(trueNegative)

fpCount <- nrow(falsePositive)

fnCount <- nrow(falseNegative)

tpCount

tnCount

fpCount

fnCount

```

```{r}

library(dplyr) 
library(readr)

# Load dataset 

treesDataset <- read_csv("arbolado-mza-dataset.csv")

rows <- nrow(treesDataset)

rows

# Get majority class

majorityClassCount <- treesDataset %>% group_by(inclinacion_peligrosa) %>% summarise(total=n())

# Show majority class

majorityClassCount

# Majority class resulted non dangerous, assign it to every tree

classifiedDataSet <- treesDataset %>% mutate(prediction_class = 0)

classifiedDataSet

# Calculate metrics

truePositive <- classifiedDataSet %>% filter(inclinacion_peligrosa == 1 & prediction_class == 1)

trueNegative <- classifiedDataSet %>% filter(inclinacion_peligrosa == 0 & prediction_class == 0)

falsePositive <- classifiedDataSet %>% filter(inclinacion_peligrosa == 0 & prediction_class == 1)

falseNegative <- classifiedDataSet %>% filter(inclinacion_peligrosa == 1 & prediction_class == 0)

tpCount <- nrow(truePositive)

tnCount <- nrow(trueNegative)

fpCount <- nrow(falsePositive)

fnCount <- nrow(falseNegative)

tpCount

tnCount

fpCount

fnCount

# Specificity and Sensitivity

sens <- (tpCount/(tpCount+fnCount))

sens

spec <- (tnCount/tnCount+fpCount)

spec 


```

```{r}
# Exercise 7

library(dplyr) 
library(readr)
library(rpart)
library(caret)

# Load dataset 

treesDataset <- read_csv("arbolado-mza-dataset.csv")

treesDataset

# Function in charge of splitting our dataframe into k folds
create_folds <- function(k,data){
   # Get row quantity
   rowsQuan <- nrow(data)
   # Number of rows in each fold
   foldsLen <- ceiling(rowsQuan/k)
   # Split data
   splittedData <- split(data, sample(rep(1:k,foldsLen)))
   return(splittedData)
}

splittedData <- create_folds(10,treesDataset)

trainIndex <- createDataPartition(as.factor(treesDataset$inclinacion_peligrosa),p=0.80,list=FALSE)


trainData <- treesDataset[ trainIndex, ]

trainData

testData <- treesDataset[ -trainIndex, ]

testData

testData[,12]

# seleccionamos la clase y las variables que nos interesan
train_formula<-formula(inclinacion_peligrosa~altura+
   circ_tronco_cm+
   lat+long+
   seccion+
   especie)
# generamos el modelo 
		tree_model<-rpart(train_formula,data=trainData)
		# obtenemos la predicción
		p<-predict(tree_model,testData,type='class') 

```